server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: AuthService
          uri: http://localhost:8081/
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}
        - id: UserService
          uri: http://localhost:8082/
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/?(?<segment>.*), /$\{segment}
